export const AGS_BAR = 'ags-bar'
export const AGS_MEDIA_PREVIEW = 'ags-media-preview'
export const AGS_LAUNCHER = 'ags-launcher'
export const AGS_NOTIFICATION = 'ags-notifications'
export const AGS_NETWORK = 'ags-network'
